before_install:
 - chmod +x gradlew

language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

install:
    - true

script:
   - ./gradlew build
